### ISSUE TITLE
Clipboard tool with German message

### ISSUE THREAD

**Issue by tiagoboldt** [Hammerspoon/Spoons#104]
The clipboardtool spoon has german and english strings. I guess it would make sense to have it all in english, considering there's no support for translations.

<img width="422" alt="43161825-1403788e-8f81-11e8-896a-b4befecc1d97" src="https://user-images.githubusercontent.com/147858/47050982-2e7e5480-d19a-11e8-9508-f4fed12ec5ea.png">

**Comment by cmsj** [comment]
@schilken what are your thoughts here?

**Comment by cmsj** [comment]
Closing since we merged an English translation.
