### ISSUE TITLE
MenubarFlag stop() and start() no work

### ISSUE THREAD

**Issue by tshu-w** [Hammerspoon/Spoons#107]
```
spoon.MenubarFlag:stop()
spoon.MenubarFlag:start()
```
this two line code doesn't restart MenubarFlag successfully. 
Maybe `prevlayout` should be set to nil in https://github.com/Hammerspoon/Spoons/blob/899e9ac8b41b9b36034eb3f846d44d71dd1e99ac/Source/MenubarFlag.spoon/init.lua#L103

**Comment by cmsj** [comment]
@Voleking that sounds like a reasonable fix. Could you edit `~/.hammerspoon/Spoons/MenubarFlag/init.lua` to try that and see if it fixes things?

**Comment by Voleking** [comment]
@cmsj Yes, it works in my case.
```lua
-- Initialize the empty indicator table
function initIndicators()
   prevlayout = nil
   if ind ~= nil then
      delIndicators()
   end
   ind = {}
end
```

**Comment by cmsj** [comment]
@zzamboni does this sound reasonable to you?

**Comment by zzamboni** [comment]
@cmsj Yes, this  sounds OK to me.
