### ISSUE TITLE
ClipShow intention?

### ISSUE THREAD

**Issue by OldGuyInTheClub** [Hammerspoon/Spoons#127]
Not an issue but a question: Is ClipShow intended as an end user tool or is it an API for invocation from other scripts?  New Hammerspoon user here - I got it installed and have MiroWindowsManager running as an alternative to Spectacle.  I am having trouble understanding how to use ClipShow - no obvious bindings etc.  I have read the docs at http://www.hammerspoon.org/Spoons/ClipShow.html

**Comment by cmsj** [comment]
AIUI you'd do your own binding/event to call http://www.hammerspoon.org/Spoons/ClipShow.html#toggleShow
