### ISSUE TITLE
passwordgenerator uses unsound methods

### ISSUE THREAD

**Issue by psifertex** [Hammerspoon/Spoons#145]
The current PasswordGenerator spoon uses Lua's `math.rand` seeded with `os.time` which is very cryptographically insecure. TL;DR randomness is hard and a plugin with the goal of generating passwords should either be very, very well vetted or (better!) just use an existing library that's known to have solid cryptographic properties.

**Comment by cmsj** [comment]
I think it might be a good idea if Hammerspoon exposed a quality random number generator from the macOS APIs, so Lua's can just be avoided entirely.

**Comment by cmsj** [comment]
Another option would be if we just unconditionally pass some high quality random number to Lua's `math.randomseed()` when we initialise the Lua interpreter. We could arguably do both options too.

**Comment by psifertex** [comment]
There are other vulnerabilities just from using a low-quality random generator even if the seed is good. If you have a higher entropy source, just use it. Only reason to avoid using it would be in situations where you're generating a large volume of rng, which seems very unlikely for hammerspoon scripts.

**Comment by cmsj** [comment]
As of fa7d0bd8 we now have both options. `math.random()` should now be well seeded, and `hs.math` exists and provides a couple of useful random number functions. This will all be available from the next Hammerspoon release. Thanks!

**Comment by psifertex** [comment]
I'm not sure this one should be closed yet -- attacks where you can predict someone's generated password completely blindly will now fail with the better seed, but it would still be trivial to predict future passwords given previous ones since the default rand is easy to predict given a few samples. I forget the minimum requirements offhand but depending on the implementation and how many samples are required  it might even be possible with a single password.  

Given that, the safest fix is to simply switch out the rand used in this spoon to the new implementation.
