### ISSUE TITLE
Issue loading MountedVolumes

### ISSUE THREAD

**Issue by daniel-beard** [Hammerspoon/Spoons#146]
```
2019-10-03 09:57:45: -- Loading Spoon: MountedVolumes
2019-10-03 09:57:45: *** ERROR: error loading module 'MountedVolumes' from file '/Users/dbeard/.hammerspoon/Spoons/MountedVolumes.spoon/init.lua':
	...dbeard/.hammerspoon/Spoons/MountedVolumes.spoon/init.lua:26: unexpected symbol near 'local'
stack traceback:
	[C]: in ?
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:552: in function 'require'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:237: in field 'loadSpoon'
	/Users/dbeard/.hammerspoon/init.lua:17: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:603: in function 'hs._coresetup.setup'
	(...tail calls...)
```

**Comment by asmagill** [comment]
Are you certain you're using the latest version of the spoon from the repository?

If you copy and paste the following into the Hammerspoon console and hit enter, what does it return?

~~~lua
r = io.open(package.searchpath("MountedVolumes", package.path), "r"):read("*a")
d = hs.fnutils.split(r, "[\r\n]")
for i = 17, 30 do print(d[i]) end
~~~

**Comment by daniel-beard** [comment]
Here's the output:

```
2019-10-04 09:08:19: local obj    = {
2019-10-04 09:08:19: -- Metadata
2019-10-04 09:08:19:     name      = "MountedVolumes",
2019-10-04 09:08:19:     author    = "A-Ron",
2019-10-04 09:08:19:     homepage  = "https://github.com/Hammerspoon/Spoons",
2019-10-04 09:08:19:     license   = "MIT - https://opensource.org/licenses/MIT",
2019-10-04 09:08:19:     spoonPath = debug.getinfo(1, "S").source:match("^@(.+/).+%.lua$"),
2019-10-04 09:08:19: }
2019-10-04 09:08:19: obj.version   = "0.2",
2019-10-04 09:08:19: local metadataKeys = {} ; for k, v in fnutils.sortByKeys(obj) do table.insert(metadataKeys, k) end
```

This is what my config looks like:

```lua
hs.loadSpoon("MountedVolumes")
spoon.MountedVolumes:start()
```

**Comment by asmagill** [comment]
Ok, somehow the zip file was created before the final edit to the spoon and an extraneous comma is still embedded in the source.

I've submitted a pull request to fix this in the zip archive, but in the mean time, you can either edit the file directly with a text editor or download the fixed zip file from https://github.com/asmagill/Spoons/raw/master/Spoons/MountedVolumes.spoon.zip

If you want to edit the file yourself, it's most likely path is `~/.hammerspoon/Spoons/MountedVolumes.spoon/init.lua` and you should change line 25 from `obj.version   = "0.2",` to `obj.version   = "0.2"` (i.e. just remove the trailing comma at the end of the line) with your preferred text editor.

Sorry about that!

**Comment by daniel-beard** [comment]
Awesome, thanks @asmagill !

**Comment by daniel-beard** [comment]
So now my config loads correctly, but I'm not able to see anything.

I've tried these, what am I doing wrong here?

```lua
hs.loadSpoon("MountedVolumes")
spoon.MountedVolumes:start()
```

```lua 
hs.loadSpoon("MountedVolumes")
spoon.MountedVolumes:show()
```

**Comment by cmsj** [comment]
Apologies for the slow movement on this, but the zip in the Spoon repository should now be correct.
