### ISSUE TITLE
BonjourLauncher.spoon `ans` variable should be local

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/Spoons#178]
Line 187 of BonjourLauncher.spoon/init.lua needs to read `local results, ans` instead of just `local results` (see https://github.com/Hammerspoon/Spoons/blob/master/Source/BonjourLauncher.spoon/init.lua#L187)

@cmsj, how do you want me to handle this? A new pull request? Edit the file within github directly? Or allow you to take care of it since this is a one-line fix and you will need to rebuild the zip files anyways,?

**Comment by cmsj** [comment]
I’ll do it, but if I forget, a PR would remind me 😁
