### ISSUE TITLE
AllBrightness not affecting LG Ultrawide

### ISSUE THREAD

**Issue by onealexharms** [Hammerspoon/Spoons#198]
I have an LG Ultrawide. Installed AllBrightness, and it didn't have any affect. (Added some alerts just to be sure I wasn't missing something.) I guess there are hs.brightness issues, dunno. Just thought I'd document.

**Comment by kyounger** [comment]
I also have an LG Ultrawide and would be happy if this worked there. Was it ever meant to?

**Comment by kyounger** [comment]
Docs suggest that it was meant for LG Ultra_Fine_  :)

http://www.hammerspoon.org/Spoons/AllBrightness.html

**Comment by onealexharms** [comment]
Oops. Yeah, I misread that.

The specs for the ultrafine say that "with seamless macOS integration, you can control volume and brightness on your 4K display without the need for physical buttons." So I'm not sure what AllBrightness would do.

Anyway, closing. Thanks.
