### ISSUE TITLE
Unintuitive Seal Query Matches

### ISSUE THREAD

**Issue by cmpadden** [Hammerspoon/Spoons#232]
While using the `Seal` Spoon, I have experienced unintuitive behavior while searching for commands. I would expect that searching for the word `Capture` would return all command results for the `screencapture` plugin, however, no results are displayed.

The search term `sc`, returns matches:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/5807118/115069435-8c9e6680-9ec1-11eb-9402-0f59ed94ba48.png">

But the search term `Scr` does not:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/5807118/115069490-a2139080-9ec1-11eb-9718-befde6439d99.png">

Please let me know if I am not using this Spoon as intended -- my configuration of the Seal spoon can be seen below.

```
spoon.SpoonInstall:andUse("Seal",
  {
    hotkeys = { show = { {"cmd"}, "space" } },
    fn = function(s)
      s:loadPlugins({
        "screencapture"
      })
      s:refreshAllCommands()
    end,
    start = true,
  }
)
```

**Edit** This may just be user error in using the Seal plugin. My initial impression was that I would be able to search for any string within a command, but I now realize that I have to prefix my search with the plugin's `cmd` value  (`sc` for `screencapture`).

https://github.com/Hammerspoon/Spoons/blob/master/Source/Seal.spoon/seal_screencapture.lua#L48

**Comment by gineer01** [comment]
"Sc" in the first screenshot matches the command `sc` in  the seal plugin screen capture, so Seal shows the choices in https://github.com/Hammerspoon/Spoons/blob/master/Source/Seal.spoon/seal_screencapture.lua#L13 . In the second screenshot, "Scr" no longer matches the command, so it doesn't show anything.

The filtering behavior depends on the specific plugin. In the `sc` case, you can see how it does filtering at this line: https://github.com/Hammerspoon/Spoons/blob/master/Source/Seal.spoon/seal_screencapture.lua#L65 . The query is the string after command: `sc <query>`

**Comment by cmpadden** [comment]
Thanks for the clarification, @gineer01. I think this "issue" boils down to user error, and me not fully understanding how Seal works. I appreciate it!
