### ISSUE TITLE
Spoon or Module?

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/Spoons#234]
@cmsj, I have a RokuRemote spoon that provides a remote control on the screen for Roku devices. Minus some documentation it still requires, it's basically ready for uploading.

It relies on another Spoon I've coded but also not uploaded that provides the actual communication with the Roku device via http... I think I originally coded it as a Spoon because it's pure Lua and I think maybe I considered merging the two, but there's really a lot of difference between the two, and this second spoon is really more of a toolkit that provides the background communication with no visuals of its own...

I'm thinking that this supporting spoon is really better suited as a module since it's designed in a way that others could easily use it to create their own interfaces or tools... Do you have guidelines on what should be a module vs Spoon?

**Comment by cmsj** [comment]
@asmagill you’ve pretty much just described how I see the split, I think a roku module sounds like a great idea for people to build all sorts of things with 🙂
