### ISSUE TITLE
How overwrite seal plugin defaults?

### ISSUE THREAD

**Issue by tami5** [Hammerspoon/Spoons#265]
Hey there, so I'm trying to overwrite appSearchPaths in seal_apps, but doing `seal.plugins.apps.appSearchPaths` doesn't get reflected. is this the right and only way todo it?

**Comment by blake** [comment]
Are you restarting Seal after modifying `appSearchPaths`? This is required per the docs. <https://www.hammerspoon.org/Spoons/Seal.plugins.apps.html#appSearchPaths>

```lua
seal.plugins.apps.appSearchPaths = {
  "<path 1>",
  "<path 2>",
}
seal.plugins.apps:restart()
```

**Comment by tami5** [comment]
Thanks @blake
