### ISSUE TITLE
Process to update Spoon repository

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/Spoons#318]
@cmsj, I'm going to have some time in the next few days to start landing some of the outstanding spoons and pull requests for Hammerspoon.

I'm not sure what the deployment process is for Hammerspoon -- that's a whole other conversation if you want me to be able to manage that (including whether or not we have a team certificate, how to handle that going forward, etc.)

But for spoons, I recall you telling me that you thought the process was pretty much automated once I commit to the master (main) branch -- but I can't find that conversation now.  So... is my recollection correct? Can I just start reviewing and merging?

Thanks!

**Comment by cmsj** [comment]
In theory yes, merging Spoons should trigger a full build/publish update, but I haven't done it in a while, so it could be broken 😬

**Comment by asmagill** [comment]
Ok, that looked like it worked for my LeftRightHotkey spoon... it created the docs.json file, created the zip file, and updated the published Spoon doc pages... I think that's all?

It will probably be Tuesday or so before I can really start reviewing the backlog here in the Spoons repository and applying them (traveling ATM, but wanted to verify the process), but I hope to have the Spoons repo up to date in the next weekish.

That still leaves the Hammerspoon repo, but ATM too much of that is tied specifically to you and your system... I can merge (and will, after catching up with the Spoons) but I can't create releases.

**Comment by asmagill** [comment]
Closing. Reopen if you think there is something that was missed in the process and needs to be addressed before I go forward.

**Comment by asmagill** [comment]
Ugh... may have spoken too soon... got an email that some jobs were not completed because they were cancelled... (see https://github.com/Hammerspoon/Spoons/actions/runs/9334839163/job/25693536338).

@cmsj, is this a problem? Like I said, the docs at https://www.hammerspoon.org/Spoons/LeftRightHotkey.html look good, and the source and zip files look good.

**Comment by asmagill** [comment]
@cmsj -- Since you seem active/available atm, figured I'd poke you about this one again -- can I safely ignore the failed jobs with Spoons? I know I can re the CI tests for Hammerspoon itself..

**Comment by cmsj** [comment]
@asmagill hmm, I'm not sure immediately why the run was cancelled, but if all the pieces look good I think let's not question it ;)

I'll work through the PRs in this repo once I'm done with a HS release, and see if anything goes wrong with those.
