### ISSUE TITLE
how to document how to use a Spoon?

### ISSUE THREAD

**Issue by dmgerman** [Hammerspoon/Spoons#321]
I recently updated a Spoon (CountDown) and created some documentation to explain how to use the Spoon (readme.org).

I realize that the page for the spoon https://www.hammerspoon.org/Spoons/CountDown.html does not link to this info.

Is there a way that I can either have this page linked to, or have this information generated into the Spoon documentation. I think one of the main challenges with using the Spoons is that the documentation documents the API, but not how a user should use the spoons.

I think the best would be to insert an optional "how to" right after the title of the Spoon in the documentation page (just above the download link).

**Comment by cmsj** [comment]
In general I would prefer it if the docs lived with the Spoon, but if the documentation is particularly large then linking out to it is fine. You can see how to do either in the `init.lua` of the OBS spoon: https://www.hammerspoon.org/Spoons/OBS.html
