### ISSUE TITLE
Adding a new spoon

### ISSUE THREAD

**Issue by asmagill** [Hammerspoon/Spoons#53]
Is there a checklist of things to do when creating a pull request with a new spoon?  I have in mind https://github.com/asmagill/hammerspoon-config/tree/master/_Spoons/MountedVolumes.spoon and it's pretty obvious where to put the source (updating the download link first), and then create a zip file.  How do I generate the html file that goes into the documentation pages and is that stored here or in another location?

**Comment by latenitefilms** [comment]
See: https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md

**Comment by cmsj** [comment]
@asmagill I generally suggest that it's easiest to just put up a PR here with the source of the Spoon and nothing else. I then run the `merge_spoon.sh` which fetches the PR, generates a current docs.json for it, zips it up and generates the website docs. The script is unfortunately hardcoded for some paths on my Mac, but I would not object in the slightest to that being fixed 😆
