### ISSUE TITLE
include link to spoon documentation

### ISSUE THREAD

**Issue by nnals** [Hammerspoon/Spoons#58]
hello,

i just clicked around https://github.com/Hammerspoon/Spoons and https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md for a while looking for some documentation on each spoon that is more readable than its docs.json file and found nothing. in the end i discovered a link to http://www.hammerspoon.org/Spoons/ on http://www.hammerspoon.org/docs/ where i should have checked first, i guess. my way of searching for the spoons documentation was certainly quite bad but still i think it would be good to include a link to http://www.hammerspoon.org/Spoons/ for example in https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md#where-do-i-get-spoons-from.

(sorry for the multitude of links)

thank you for all your work!
nicolai

**Comment by cmsj** [comment]
Agreed, thanks for pointing this out. I have modified the Where Do I Get Spoons From section to link first to hammerspoon.org/Spoons :)

**Comment by cmsj** [comment]
and a link on the README.md for this repo just to make sure the link is everywhere :)

**Comment by latenitefilms** [comment]
@cmsj - Might be worth mentioning Spoons on front page of http://www.hammerspoon.org as well?

**Comment by cmsj** [comment]
@latenitefilms interesting, see my suggestion on #56 just now.

**Comment by latenitefilms** [comment]
@cmsj - Sounds good! However, I still still spoons should get a mention on the front page, as it is a pretty powerful feature of Hammerspoon now.
