### ISSUE TITLE
Images to help describing a spoon?

### ISSUE THREAD

**Issue by casouri** [Hammerspoon/Spoons#76]
Right now none of the descriptions of the spoons has images. It is fine for some of the spoons, but for others, it is hard to imagine what is the spoon like without any visual presentation.

Is there any way to add images to official spoon page? Or a wiki page presenting spoons?

**Comment by cmsj** [comment]
All of our web stuff is hosted on github and uses Markdown, so it ought to be possible to include images and have them be hosted/served from the Spoons git repo.

If someone wants to start including images, I'd suggest starting with a simple PR so we can hash out the details of how the folders/URLs will work.
