### ISSUE TITLE
Link to documentation of Seal's submodule is broken

### ISSUE THREAD

**Issue by casouri** [Hammerspoon/Spoons#78]
http://www.hammerspoon.org/Spoons/Seal.plugins.html

**Comment by ideologysec** [comment]
http://www.hammerspoon.org/Spoons/Seal.html

**Comment by casouri** [comment]
That link is fine, but if you go into the **submodules**, it will show you 404.

**Comment by cmsj** [comment]
This should now be fixed. Thanks!
