### ISSUE TITLE
CountDown doesn't draw anything

### ISSUE THREAD

**Issue by whitemuu** [Hammerspoon/Spoons#81]
CountDown doesn't draw anything, just show a notification when finished.
And the console prints no abnormal message.

I'm using El Capitan 10.11.4

**Comment by whitemuu** [comment]
Oh my! there it is! I was expecting a big number showing in the centre of the screen and the colour is a bit light. After you told me where it is, now I can't get rid of it from my eye😂.

Thank you!

**Comment by ashfinal** [comment]
Well, the whole point is I hope CountDown runs in a distraction-free way. (But when you wanna see the percent of progress bar, yes, there it is.)

I hope you like the idea. But if you don't, there is code you can modify to suit your needs. That's also a point of OSS. :)
