### ISSUE TITLE
Emoji Spoon takes 30sec to load, causes Hammerspoon to "Not Responding" while loading

### ISSUE THREAD

**Issue by ideologysec** [Hammerspoon/Spoons#82]
I cannot imagine a world where parsing JSON and loading 2300+ images into memory is fast; nonetheless, the emoji spoon is very very slow, and it causes Hammerspoon to hang and be unresponsive for roughly 30 seconds. I narrowed it down to this spoon by removing the init lines from my init.lua, and Hammerspoon reload times dropped to 2-3 seconds.

Are there any Lua or Hammerspoon profiling tools such that I can see how long each operation takes? (it looks like there might be some opportunity for optimization just based on the fact that the spoon is both inserting in sorted order, and then sorting the table...again?)

**Comment by latenitefilms** [comment]
We have a very basic benchmarking tool [here](https://github.com/CommandPost/CommandPost/blob/develop/src/extensions/cp/bench/init.lua) which may be of interest?

**Comment by ideologysec** [comment]
If I was more awake, maybe I'd understand how to use it. I'll take a look tomorrow or Saturday. Thanks.

**Comment by aldur** [comment]
Hi, I'm the author of the Spoon emoji. A user submitted a fix to my dotfiles repository for the slow loading, I will pull it here as soon as I have a second :) Thanks for reporting it!

**Comment by cmsj** [comment]
PR is merged. Thanks!
