### ISSUE TITLE
Add start() and stop() methods to SpeedMenu so it doesn't have to be on all the time

### ISSUE THREAD

**Issue by malob** [Hammerspoon/Spoons#83]
I like the SpeedMenu spoon, but I don't always like having it on. It would be nice if it provided `start()` and `stop()` methods. So I could turn it on/off.

**Comment by cmsj** [comment]
Ping @ashfinal :)

**Comment by ashfinal** [comment]
Sorry for late reply. I don’t think it’s a good idea to add those two methods. 

You can always to stop SpeedMenu by removing SpeedMenu spoon in your Hammerspoon config.

**Comment by malob** [comment]
No worries, thanks for responding!

What I’d like to be able to do though is easily stop and start it without having to go in and edit my config. E.g., by setting up a Seal User Action or a keyboard shortcut.

The use case is that I do like having that information available sometimes but not all the time, and it would be nice to be able to quickly toggle it on or off as needed.

Also from the [Hammerspoon Spoon Plugins Documentation](https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md) is seems like this is the recommended standard implementation:

> In most cases, the API should take roughly this form:
> * NAME:init() - this is called automatically by hs.loadSpoon() and will do any initial setup work required, but should generally not start taking any actions
> * NAME:start() - if any kind of background work is necessary, this method will start it
> * NAME:stop() - if any kind of background work is running, this method will stop it

**Comment by malob** [comment]
@ashfinal, I went ahead and implemented this functionality myself, and just initiated a pull request for your consideration. See pull request #93.

**Comment by ashfinal** [comment]
@malob Good to know you implemented this functionality yourself! IMHO, the point of SpeedMenu is whenever you want you can *always* get the condition of your network by simply taking a glance. I'd like Spoons be as easily used as possible, without more configuration.

Adding this functionality is a good thing.  My only hope is it's default on once this Spoon is loaded.

**Comment by malob** [comment]
Closed by #93.
