### ISSUE TITLE
Seal.plugins.useractions passes ".*" as argument to `fn` when keyword is used alone

### ISSUE THREAD

**Issue by malob** [Hammerspoon/Spoons#84]
I sometimes want to create actions with keywords, and want the actions to have some default behavior if nothing is provided after the keyword.

Currently when the keyword is used alone the argument to `fn` is ".*". This seems odd to me. Off the top of my head, `nil` or an empty string seem like the two most sensible alternatives.

**Comment by cmsj** [comment]
Ping @zzamboni :)

**Comment by malob** [comment]
❤️
