### ISSUE TITLE
Seal.plugins.useractions errors out if hotkey and keyword are used together

### ISSUE THREAD

**Issue by malob** [Hammerspoon/Spoons#85]
I sometimes want to create an action with a keyword, but that also has some default behavior if invoked with a hotkey. However, when I set this up, I get an error when using the hotkey.

Here's a minimal example:
```lua
        ["Test"] = {
          fn = function(x)
            print("test")
          end,
          keyword = "test",
          hotkey = {hyper, "t"}
        }
```

Expected behavior:
* Typing "test" into Seal prints "test" to console.
* Pressing hyper+t prints "test" to console.

Actual behavior:
* Typing "test" into Seal prints "test" to console.
* Pressing hyper+t generates an error
```
2018-05-30 08:17:47: ********
2018-05-30 08:17:47: 08:17:47 ERROR:   LuaSkin: hs.hotkey callback: ...nfig/hammerspoon/Spoons/Seal.spoon//seal_useractions.lua:246: attempt to index a nil value (local 'row')
stack traceback:
	...nfig/hammerspoon/Spoons/Seal.spoon//seal_useractions.lua:246: in function <...nfig/hammerspoon/Spoons/Seal.spoon//seal_useractions.lua:244>
	(...tail calls...)
2018-05-30 08:17:47: ********
```

I think what I'd want is for the function defined in `fn` to be called with either `nil` or an empty string passed as the argument when the action is invoked with the hotkey.

**Comment by cmsj** [comment]
ping @zzamboni :)

**Comment by malob** [comment]
❤️
